[weaviate]
url = "https://your-weaviate-cluster.weaviate.network"
api_key = "your-weaviate-api-key"
[mongodb]
connection_string = "mongodb+srv://arbazdogar20:qcHwne70Vj8WgOBy@personalized-wellness-p.ruft5zh.mongodb.net/personalized-wellness?retryWrites=true&w=majority